import { StyleSheet } from '@react-pdf/renderer';

export const colors = {
  bg: '#0A0A0F',
  bgCard: '#141420',
  bgCardAlt: '#1A1A2E',
  accent: '#8B5CF6',
  accentLight: '#A78BFA',
  accentPink: '#EC4899',
  text: '#E5E5E5',
  textMuted: '#9CA3AF',
  textBright: '#FFFFFF',
  green: '#10B981',
  yellow: '#F59E0B',
  red: '#EF4444',
  border: '#2D2D44',
};

export const styles = StyleSheet.create({
  page: {
    backgroundColor: colors.bg,
    color: colors.text,
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 11,
  },
  coverPage: {
    backgroundColor: colors.bg,
    padding: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  h1: {
    fontSize: 28,
    fontFamily: 'Helvetica-Bold',
    color: colors.textBright,
    marginBottom: 8,
  },
  h2: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: colors.textBright,
    marginBottom: 12,
  },
  h3: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: colors.accentLight,
    marginBottom: 8,
  },
  body: {
    fontSize: 11,
    color: colors.text,
    lineHeight: 1.6,
    marginBottom: 8,
  },
  muted: {
    fontSize: 10,
    color: colors.textMuted,
    lineHeight: 1.5,
  },
  card: {
    backgroundColor: colors.bgCard,
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    border: `1px solid ${colors.border}`,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  spaceBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badge: {
    backgroundColor: colors.accent,
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 9,
    color: colors.textBright,
    fontFamily: 'Helvetica-Bold',
  },
  badgeGreen: {
    backgroundColor: colors.green,
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 9,
    color: colors.textBright,
    fontFamily: 'Helvetica-Bold',
  },
  badgeYellow: {
    backgroundColor: colors.yellow,
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 9,
    color: colors.bg,
    fontFamily: 'Helvetica-Bold',
  },
  badgeRed: {
    backgroundColor: colors.red,
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 9,
    color: colors.textBright,
    fontFamily: 'Helvetica-Bold',
  },
  divider: {
    borderBottom: `1px solid ${colors.border}`,
    marginVertical: 12,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 8,
    color: colors.textMuted,
    textAlign: 'center',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 20,
    right: 40,
    fontSize: 8,
    color: colors.textMuted,
  },
});
